services:
  toolbox:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: toolbox
    platform: linux/amd64
    network_mode: "host"
    volumes:
      - ./tools.yaml:/app/tools.yaml
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata1:
